### PR TITLE
fix: allow netresearch/jsonmapper ^3.0 and ^4.0

### LINKED ISSUE #51: please add compatibility with netresearch/jsonmapper ^3 and ^4
There are two new major versions of netresearch/jsonmapper which as far as I can see only break BC by dropping support for old versions of PHP and PHPUnit.

Right now this package's constraint on versions ^1 or ^2 seems to stop us from updating our project to the current version of jsonmapper (through vimeo/psalm 🤷).

### PR DESCRIPTION
**Pull request by umesecke**
Fixes #51

### CODE REVIEW

**Comment by sanderg93** [comment]
Can this be merged?

**Comment by Pe46dro** [comment]
Poke @felixfbecker

**Comment by djairhogeuens** [comment]
Waiting for this one as well @felixfbecker

**Comment by weirdan** [comment]
@felixfbecker could you please merge this when you have a free moment?

**Pull request merged**
