### PR TITLE
ci: fix problems in Travis CI configuration

### PR DESCRIPTION
**Pull request by szepeviktor**
kép

If you log in to Travis you can see these validation results.

- put config in chronological order
- quote YAML floating point numbers
- proper use of job matrix
- fix npm caching

### CODE REVIEW

**Comment by szepeviktor** [comment]
kép

Fixing...

**Comment by szepeviktor** [comment]
Oh no!
https://travis-ci.community/t/always-show-allow-failures-allowed-failures-when-build-stages-are-used/217

**Comment by felixfbecker** [comment]
I think better would also be to migrate to GitHub actions (#46), Travis has become really unreliable

**Pull request merged**
